/*
F5 Distributed Cloud Services API for ves.io.schema.views.origin_pool

Testing DefaultAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	openapiclient "github.com/pranavskumar/MySDK"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
)

func Test_openapi_DefaultAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test DefaultAPIService VesIoSchemaViewsOriginPoolAPICreate", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var metadataNamespace string

		resp, httpRes, err := apiClient.DefaultAPI.VesIoSchemaViewsOriginPoolAPICreate(context.Background(), metadataNamespace).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultAPIService VesIoSchemaViewsOriginPoolAPIDelete", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var namespace string
		var name string

		resp, httpRes, err := apiClient.DefaultAPI.VesIoSchemaViewsOriginPoolAPIDelete(context.Background(), namespace, name).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultAPIService VesIoSchemaViewsOriginPoolAPIGet", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var namespace string
		var name string

		resp, httpRes, err := apiClient.DefaultAPI.VesIoSchemaViewsOriginPoolAPIGet(context.Background(), namespace, name).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultAPIService VesIoSchemaViewsOriginPoolAPIList", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var namespace string

		resp, httpRes, err := apiClient.DefaultAPI.VesIoSchemaViewsOriginPoolAPIList(context.Background(), namespace).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultAPIService VesIoSchemaViewsOriginPoolAPIReplace", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var metadataNamespace string
		var metadataName string

		resp, httpRes, err := apiClient.DefaultAPI.VesIoSchemaViewsOriginPoolAPIReplace(context.Background(), metadataNamespace, metadataName).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
