/*
F5 Distributed Cloud Services API for ves.io.schema.views.origin_pool

Origin pool is a view to create cluster and endpoints that can be used in HTTP loadbalancer or TCP loadbalancer  It will create following child objects  * cluster * endpoints * healthcheck

API version: 
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// OriginPoolGetResponseFormatCode x-displayName: \"Get Response Format\" This is the various forms that can be requested to be sent in the GetResponse   - GET_RSP_FORMAT_DEFAULT: x-displayName: \"Default Format\" Default format of returned resource  - GET_RSP_FORMAT_FOR_CREATE: x-displayName: \"Create request Format\" Response should be in CreateRequest format  - GET_RSP_FORMAT_FOR_REPLACE: x-displayName: \"Replace request format\" Response should be in ReplaceRequest format  - GET_RSP_FORMAT_READ: x-displayName: \"GetSpecType format\" Response should be in format of GetSpecType  - GET_RSP_FORMAT_REFERRING_OBJECTS: x-displayName: \"Referring Objects\" Response should have other objects referring to this object  - GET_RSP_FORMAT_BROKEN_REFERENCES: x-displayName: \"Broken Referred Objects\" Response should have deleted and disabled objects referrred by this object
type OriginPoolGetResponseFormatCode string

// List of origin_poolGetResponseFormatCode
const (
	DEFAULT_ OriginPoolGetResponseFormatCode = "GET_RSP_FORMAT_DEFAULT"
	FOR_CREATE OriginPoolGetResponseFormatCode = "GET_RSP_FORMAT_FOR_CREATE"
	FOR_REPLACE OriginPoolGetResponseFormatCode = "GET_RSP_FORMAT_FOR_REPLACE"
	READ OriginPoolGetResponseFormatCode = "GET_RSP_FORMAT_READ"
	REFERRING_OBJECTS OriginPoolGetResponseFormatCode = "GET_RSP_FORMAT_REFERRING_OBJECTS"
	BROKEN_REFERENCES OriginPoolGetResponseFormatCode = "GET_RSP_FORMAT_BROKEN_REFERENCES"
)

// All allowed values of OriginPoolGetResponseFormatCode enum
var AllowedOriginPoolGetResponseFormatCodeEnumValues = []OriginPoolGetResponseFormatCode{
	"GET_RSP_FORMAT_DEFAULT",
	"GET_RSP_FORMAT_FOR_CREATE",
	"GET_RSP_FORMAT_FOR_REPLACE",
	"GET_RSP_FORMAT_READ",
	"GET_RSP_FORMAT_REFERRING_OBJECTS",
	"GET_RSP_FORMAT_BROKEN_REFERENCES",
}

func (v *OriginPoolGetResponseFormatCode) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := OriginPoolGetResponseFormatCode(value)
	for _, existing := range AllowedOriginPoolGetResponseFormatCodeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid OriginPoolGetResponseFormatCode", value)
}

// NewOriginPoolGetResponseFormatCodeFromValue returns a pointer to a valid OriginPoolGetResponseFormatCode
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewOriginPoolGetResponseFormatCodeFromValue(v string) (*OriginPoolGetResponseFormatCode, error) {
	ev := OriginPoolGetResponseFormatCode(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for OriginPoolGetResponseFormatCode: valid values are %v", v, AllowedOriginPoolGetResponseFormatCodeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v OriginPoolGetResponseFormatCode) IsValid() bool {
	for _, existing := range AllowedOriginPoolGetResponseFormatCodeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to origin_poolGetResponseFormatCode value
func (v OriginPoolGetResponseFormatCode) Ptr() *OriginPoolGetResponseFormatCode {
	return &v
}

type NullableOriginPoolGetResponseFormatCode struct {
	value *OriginPoolGetResponseFormatCode
	isSet bool
}

func (v NullableOriginPoolGetResponseFormatCode) Get() *OriginPoolGetResponseFormatCode {
	return v.value
}

func (v *NullableOriginPoolGetResponseFormatCode) Set(val *OriginPoolGetResponseFormatCode) {
	v.value = val
	v.isSet = true
}

func (v NullableOriginPoolGetResponseFormatCode) IsSet() bool {
	return v.isSet
}

func (v *NullableOriginPoolGetResponseFormatCode) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOriginPoolGetResponseFormatCode(val *OriginPoolGetResponseFormatCode) *NullableOriginPoolGetResponseFormatCode {
	return &NullableOriginPoolGetResponseFormatCode{value: val, isSet: true}
}

func (v NullableOriginPoolGetResponseFormatCode) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOriginPoolGetResponseFormatCode) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

