/*
F5 Distributed Cloud Services API for ves.io.schema.views.origin_pool

Origin pool is a view to create cluster and endpoints that can be used in HTTP loadbalancer or TCP loadbalancer  It will create following child objects  * cluster * endpoints * healthcheck

API version: 
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the OriginPoolObject type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OriginPoolObject{}

// OriginPoolObject Origin pool view object
type OriginPoolObject struct {
	Metadata *SchemaObjectMetaType `json:"metadata,omitempty"`
	Spec *OriginPoolSpecType `json:"spec,omitempty"`
	SystemMetadata *SchemaSystemObjectMetaType `json:"system_metadata,omitempty"`
}

// NewOriginPoolObject instantiates a new OriginPoolObject object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOriginPoolObject() *OriginPoolObject {
	this := OriginPoolObject{}
	return &this
}

// NewOriginPoolObjectWithDefaults instantiates a new OriginPoolObject object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOriginPoolObjectWithDefaults() *OriginPoolObject {
	this := OriginPoolObject{}
	return &this
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *OriginPoolObject) GetMetadata() SchemaObjectMetaType {
	if o == nil || IsNil(o.Metadata) {
		var ret SchemaObjectMetaType
		return ret
	}
	return *o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OriginPoolObject) GetMetadataOk() (*SchemaObjectMetaType, bool) {
	if o == nil || IsNil(o.Metadata) {
		return nil, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *OriginPoolObject) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given SchemaObjectMetaType and assigns it to the Metadata field.
func (o *OriginPoolObject) SetMetadata(v SchemaObjectMetaType) {
	o.Metadata = &v
}

// GetSpec returns the Spec field value if set, zero value otherwise.
func (o *OriginPoolObject) GetSpec() OriginPoolSpecType {
	if o == nil || IsNil(o.Spec) {
		var ret OriginPoolSpecType
		return ret
	}
	return *o.Spec
}

// GetSpecOk returns a tuple with the Spec field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OriginPoolObject) GetSpecOk() (*OriginPoolSpecType, bool) {
	if o == nil || IsNil(o.Spec) {
		return nil, false
	}
	return o.Spec, true
}

// HasSpec returns a boolean if a field has been set.
func (o *OriginPoolObject) HasSpec() bool {
	if o != nil && !IsNil(o.Spec) {
		return true
	}

	return false
}

// SetSpec gets a reference to the given OriginPoolSpecType and assigns it to the Spec field.
func (o *OriginPoolObject) SetSpec(v OriginPoolSpecType) {
	o.Spec = &v
}

// GetSystemMetadata returns the SystemMetadata field value if set, zero value otherwise.
func (o *OriginPoolObject) GetSystemMetadata() SchemaSystemObjectMetaType {
	if o == nil || IsNil(o.SystemMetadata) {
		var ret SchemaSystemObjectMetaType
		return ret
	}
	return *o.SystemMetadata
}

// GetSystemMetadataOk returns a tuple with the SystemMetadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OriginPoolObject) GetSystemMetadataOk() (*SchemaSystemObjectMetaType, bool) {
	if o == nil || IsNil(o.SystemMetadata) {
		return nil, false
	}
	return o.SystemMetadata, true
}

// HasSystemMetadata returns a boolean if a field has been set.
func (o *OriginPoolObject) HasSystemMetadata() bool {
	if o != nil && !IsNil(o.SystemMetadata) {
		return true
	}

	return false
}

// SetSystemMetadata gets a reference to the given SchemaSystemObjectMetaType and assigns it to the SystemMetadata field.
func (o *OriginPoolObject) SetSystemMetadata(v SchemaSystemObjectMetaType) {
	o.SystemMetadata = &v
}

func (o OriginPoolObject) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OriginPoolObject) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}
	if !IsNil(o.Spec) {
		toSerialize["spec"] = o.Spec
	}
	if !IsNil(o.SystemMetadata) {
		toSerialize["system_metadata"] = o.SystemMetadata
	}
	return toSerialize, nil
}

type NullableOriginPoolObject struct {
	value *OriginPoolObject
	isSet bool
}

func (v NullableOriginPoolObject) Get() *OriginPoolObject {
	return v.value
}

func (v *NullableOriginPoolObject) Set(val *OriginPoolObject) {
	v.value = val
	v.isSet = true
}

func (v NullableOriginPoolObject) IsSet() bool {
	return v.isSet
}

func (v *NullableOriginPoolObject) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOriginPoolObject(val *OriginPoolObject) *NullableOriginPoolObject {
	return &NullableOriginPoolObject{value: val, isSet: true}
}

func (v NullableOriginPoolObject) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOriginPoolObject) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


