/*
F5 Distributed Cloud Services API for ves.io.schema.views.origin_pool

Origin pool is a view to create cluster and endpoints that can be used in HTTP loadbalancer or TCP loadbalancer  It will create following child objects  * cluster * endpoints * healthcheck

API version: 
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the OriginPoolGetResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OriginPoolGetResponse{}

// OriginPoolGetResponse This is the output message of the 'Get' RPC
type OriginPoolGetResponse struct {
	CreateForm *OriginPoolCreateRequest `json:"create_form,omitempty"`
	// The set of deleted objects that are referred by this object
	DeletedReferredObjects []IoschemaObjectRefType `json:"deleted_referred_objects,omitempty"`
	// The set of deleted objects that are referred by this object
	DisabledReferredObjects []IoschemaObjectRefType `json:"disabled_referred_objects,omitempty"`
	Metadata *SchemaObjectGetMetaType `json:"metadata,omitempty"`
	Object *OriginPoolObject `json:"object,omitempty"`
	// The set of objects that are referring to this object in their spec
	ReferringObjects []IoschemaObjectRefType `json:"referring_objects,omitempty"`
	ReplaceForm *OriginPoolReplaceRequest `json:"replace_form,omitempty"`
	Spec *ViewsoriginPoolGetSpecType `json:"spec,omitempty"`
	SystemMetadata *SchemaSystemObjectGetMetaType `json:"system_metadata,omitempty"`
}

// NewOriginPoolGetResponse instantiates a new OriginPoolGetResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOriginPoolGetResponse() *OriginPoolGetResponse {
	this := OriginPoolGetResponse{}
	return &this
}

// NewOriginPoolGetResponseWithDefaults instantiates a new OriginPoolGetResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOriginPoolGetResponseWithDefaults() *OriginPoolGetResponse {
	this := OriginPoolGetResponse{}
	return &this
}

// GetCreateForm returns the CreateForm field value if set, zero value otherwise.
func (o *OriginPoolGetResponse) GetCreateForm() OriginPoolCreateRequest {
	if o == nil || IsNil(o.CreateForm) {
		var ret OriginPoolCreateRequest
		return ret
	}
	return *o.CreateForm
}

// GetCreateFormOk returns a tuple with the CreateForm field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OriginPoolGetResponse) GetCreateFormOk() (*OriginPoolCreateRequest, bool) {
	if o == nil || IsNil(o.CreateForm) {
		return nil, false
	}
	return o.CreateForm, true
}

// HasCreateForm returns a boolean if a field has been set.
func (o *OriginPoolGetResponse) HasCreateForm() bool {
	if o != nil && !IsNil(o.CreateForm) {
		return true
	}

	return false
}

// SetCreateForm gets a reference to the given OriginPoolCreateRequest and assigns it to the CreateForm field.
func (o *OriginPoolGetResponse) SetCreateForm(v OriginPoolCreateRequest) {
	o.CreateForm = &v
}

// GetDeletedReferredObjects returns the DeletedReferredObjects field value if set, zero value otherwise.
func (o *OriginPoolGetResponse) GetDeletedReferredObjects() []IoschemaObjectRefType {
	if o == nil || IsNil(o.DeletedReferredObjects) {
		var ret []IoschemaObjectRefType
		return ret
	}
	return o.DeletedReferredObjects
}

// GetDeletedReferredObjectsOk returns a tuple with the DeletedReferredObjects field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OriginPoolGetResponse) GetDeletedReferredObjectsOk() ([]IoschemaObjectRefType, bool) {
	if o == nil || IsNil(o.DeletedReferredObjects) {
		return nil, false
	}
	return o.DeletedReferredObjects, true
}

// HasDeletedReferredObjects returns a boolean if a field has been set.
func (o *OriginPoolGetResponse) HasDeletedReferredObjects() bool {
	if o != nil && !IsNil(o.DeletedReferredObjects) {
		return true
	}

	return false
}

// SetDeletedReferredObjects gets a reference to the given []IoschemaObjectRefType and assigns it to the DeletedReferredObjects field.
func (o *OriginPoolGetResponse) SetDeletedReferredObjects(v []IoschemaObjectRefType) {
	o.DeletedReferredObjects = v
}

// GetDisabledReferredObjects returns the DisabledReferredObjects field value if set, zero value otherwise.
func (o *OriginPoolGetResponse) GetDisabledReferredObjects() []IoschemaObjectRefType {
	if o == nil || IsNil(o.DisabledReferredObjects) {
		var ret []IoschemaObjectRefType
		return ret
	}
	return o.DisabledReferredObjects
}

// GetDisabledReferredObjectsOk returns a tuple with the DisabledReferredObjects field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OriginPoolGetResponse) GetDisabledReferredObjectsOk() ([]IoschemaObjectRefType, bool) {
	if o == nil || IsNil(o.DisabledReferredObjects) {
		return nil, false
	}
	return o.DisabledReferredObjects, true
}

// HasDisabledReferredObjects returns a boolean if a field has been set.
func (o *OriginPoolGetResponse) HasDisabledReferredObjects() bool {
	if o != nil && !IsNil(o.DisabledReferredObjects) {
		return true
	}

	return false
}

// SetDisabledReferredObjects gets a reference to the given []IoschemaObjectRefType and assigns it to the DisabledReferredObjects field.
func (o *OriginPoolGetResponse) SetDisabledReferredObjects(v []IoschemaObjectRefType) {
	o.DisabledReferredObjects = v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *OriginPoolGetResponse) GetMetadata() SchemaObjectGetMetaType {
	if o == nil || IsNil(o.Metadata) {
		var ret SchemaObjectGetMetaType
		return ret
	}
	return *o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OriginPoolGetResponse) GetMetadataOk() (*SchemaObjectGetMetaType, bool) {
	if o == nil || IsNil(o.Metadata) {
		return nil, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *OriginPoolGetResponse) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given SchemaObjectGetMetaType and assigns it to the Metadata field.
func (o *OriginPoolGetResponse) SetMetadata(v SchemaObjectGetMetaType) {
	o.Metadata = &v
}

// GetObject returns the Object field value if set, zero value otherwise.
func (o *OriginPoolGetResponse) GetObject() OriginPoolObject {
	if o == nil || IsNil(o.Object) {
		var ret OriginPoolObject
		return ret
	}
	return *o.Object
}

// GetObjectOk returns a tuple with the Object field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OriginPoolGetResponse) GetObjectOk() (*OriginPoolObject, bool) {
	if o == nil || IsNil(o.Object) {
		return nil, false
	}
	return o.Object, true
}

// HasObject returns a boolean if a field has been set.
func (o *OriginPoolGetResponse) HasObject() bool {
	if o != nil && !IsNil(o.Object) {
		return true
	}

	return false
}

// SetObject gets a reference to the given OriginPoolObject and assigns it to the Object field.
func (o *OriginPoolGetResponse) SetObject(v OriginPoolObject) {
	o.Object = &v
}

// GetReferringObjects returns the ReferringObjects field value if set, zero value otherwise.
func (o *OriginPoolGetResponse) GetReferringObjects() []IoschemaObjectRefType {
	if o == nil || IsNil(o.ReferringObjects) {
		var ret []IoschemaObjectRefType
		return ret
	}
	return o.ReferringObjects
}

// GetReferringObjectsOk returns a tuple with the ReferringObjects field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OriginPoolGetResponse) GetReferringObjectsOk() ([]IoschemaObjectRefType, bool) {
	if o == nil || IsNil(o.ReferringObjects) {
		return nil, false
	}
	return o.ReferringObjects, true
}

// HasReferringObjects returns a boolean if a field has been set.
func (o *OriginPoolGetResponse) HasReferringObjects() bool {
	if o != nil && !IsNil(o.ReferringObjects) {
		return true
	}

	return false
}

// SetReferringObjects gets a reference to the given []IoschemaObjectRefType and assigns it to the ReferringObjects field.
func (o *OriginPoolGetResponse) SetReferringObjects(v []IoschemaObjectRefType) {
	o.ReferringObjects = v
}

// GetReplaceForm returns the ReplaceForm field value if set, zero value otherwise.
func (o *OriginPoolGetResponse) GetReplaceForm() OriginPoolReplaceRequest {
	if o == nil || IsNil(o.ReplaceForm) {
		var ret OriginPoolReplaceRequest
		return ret
	}
	return *o.ReplaceForm
}

// GetReplaceFormOk returns a tuple with the ReplaceForm field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OriginPoolGetResponse) GetReplaceFormOk() (*OriginPoolReplaceRequest, bool) {
	if o == nil || IsNil(o.ReplaceForm) {
		return nil, false
	}
	return o.ReplaceForm, true
}

// HasReplaceForm returns a boolean if a field has been set.
func (o *OriginPoolGetResponse) HasReplaceForm() bool {
	if o != nil && !IsNil(o.ReplaceForm) {
		return true
	}

	return false
}

// SetReplaceForm gets a reference to the given OriginPoolReplaceRequest and assigns it to the ReplaceForm field.
func (o *OriginPoolGetResponse) SetReplaceForm(v OriginPoolReplaceRequest) {
	o.ReplaceForm = &v
}

// GetSpec returns the Spec field value if set, zero value otherwise.
func (o *OriginPoolGetResponse) GetSpec() ViewsoriginPoolGetSpecType {
	if o == nil || IsNil(o.Spec) {
		var ret ViewsoriginPoolGetSpecType
		return ret
	}
	return *o.Spec
}

// GetSpecOk returns a tuple with the Spec field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OriginPoolGetResponse) GetSpecOk() (*ViewsoriginPoolGetSpecType, bool) {
	if o == nil || IsNil(o.Spec) {
		return nil, false
	}
	return o.Spec, true
}

// HasSpec returns a boolean if a field has been set.
func (o *OriginPoolGetResponse) HasSpec() bool {
	if o != nil && !IsNil(o.Spec) {
		return true
	}

	return false
}

// SetSpec gets a reference to the given ViewsoriginPoolGetSpecType and assigns it to the Spec field.
func (o *OriginPoolGetResponse) SetSpec(v ViewsoriginPoolGetSpecType) {
	o.Spec = &v
}

// GetSystemMetadata returns the SystemMetadata field value if set, zero value otherwise.
func (o *OriginPoolGetResponse) GetSystemMetadata() SchemaSystemObjectGetMetaType {
	if o == nil || IsNil(o.SystemMetadata) {
		var ret SchemaSystemObjectGetMetaType
		return ret
	}
	return *o.SystemMetadata
}

// GetSystemMetadataOk returns a tuple with the SystemMetadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OriginPoolGetResponse) GetSystemMetadataOk() (*SchemaSystemObjectGetMetaType, bool) {
	if o == nil || IsNil(o.SystemMetadata) {
		return nil, false
	}
	return o.SystemMetadata, true
}

// HasSystemMetadata returns a boolean if a field has been set.
func (o *OriginPoolGetResponse) HasSystemMetadata() bool {
	if o != nil && !IsNil(o.SystemMetadata) {
		return true
	}

	return false
}

// SetSystemMetadata gets a reference to the given SchemaSystemObjectGetMetaType and assigns it to the SystemMetadata field.
func (o *OriginPoolGetResponse) SetSystemMetadata(v SchemaSystemObjectGetMetaType) {
	o.SystemMetadata = &v
}

func (o OriginPoolGetResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OriginPoolGetResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CreateForm) {
		toSerialize["create_form"] = o.CreateForm
	}
	if !IsNil(o.DeletedReferredObjects) {
		toSerialize["deleted_referred_objects"] = o.DeletedReferredObjects
	}
	if !IsNil(o.DisabledReferredObjects) {
		toSerialize["disabled_referred_objects"] = o.DisabledReferredObjects
	}
	if !IsNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}
	if !IsNil(o.Object) {
		toSerialize["object"] = o.Object
	}
	if !IsNil(o.ReferringObjects) {
		toSerialize["referring_objects"] = o.ReferringObjects
	}
	if !IsNil(o.ReplaceForm) {
		toSerialize["replace_form"] = o.ReplaceForm
	}
	if !IsNil(o.Spec) {
		toSerialize["spec"] = o.Spec
	}
	if !IsNil(o.SystemMetadata) {
		toSerialize["system_metadata"] = o.SystemMetadata
	}
	return toSerialize, nil
}

type NullableOriginPoolGetResponse struct {
	value *OriginPoolGetResponse
	isSet bool
}

func (v NullableOriginPoolGetResponse) Get() *OriginPoolGetResponse {
	return v.value
}

func (v *NullableOriginPoolGetResponse) Set(val *OriginPoolGetResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableOriginPoolGetResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableOriginPoolGetResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOriginPoolGetResponse(val *OriginPoolGetResponse) *NullableOriginPoolGetResponse {
	return &NullableOriginPoolGetResponse{value: val, isSet: true}
}

func (v NullableOriginPoolGetResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOriginPoolGetResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


