/*
F5 Distributed Cloud Services API for ves.io.schema.views.origin_pool

Origin pool is a view to create cluster and endpoints that can be used in HTTP loadbalancer or TCP loadbalancer  It will create following child objects  * cluster * endpoints * healthcheck

API version: 
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the OriginPoolOriginServerPublicName type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OriginPoolOriginServerPublicName{}

// OriginPoolOriginServerPublicName Specify origin server with public DNS name
type OriginPoolOriginServerPublicName struct {
	//  DNS Name  Example: ` \"value\"`  Required: YES  Validation Rules:   ves.io.schema.rules.message.required: true   ves.io.schema.rules.string.hostname: true   ves.io.schema.rules.string.max_len: 256   ves.io.schema.rules.string.min_len: 1 
	DnsName *string `json:"dns_name,omitempty"`
	//  Interval for DNS refresh in seconds.  Max value is 7 days as per https://datatracker.ietf.org/doc/html/rfc8767  Example: ` \"20\"`  Validation Rules:   ves.io.schema.rules.uint32.lte: 604800 
	RefreshInterval *int64 `json:"refresh_interval,omitempty"`
}

// NewOriginPoolOriginServerPublicName instantiates a new OriginPoolOriginServerPublicName object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOriginPoolOriginServerPublicName() *OriginPoolOriginServerPublicName {
	this := OriginPoolOriginServerPublicName{}
	return &this
}

// NewOriginPoolOriginServerPublicNameWithDefaults instantiates a new OriginPoolOriginServerPublicName object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOriginPoolOriginServerPublicNameWithDefaults() *OriginPoolOriginServerPublicName {
	this := OriginPoolOriginServerPublicName{}
	return &this
}

// GetDnsName returns the DnsName field value if set, zero value otherwise.
func (o *OriginPoolOriginServerPublicName) GetDnsName() string {
	if o == nil || IsNil(o.DnsName) {
		var ret string
		return ret
	}
	return *o.DnsName
}

// GetDnsNameOk returns a tuple with the DnsName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OriginPoolOriginServerPublicName) GetDnsNameOk() (*string, bool) {
	if o == nil || IsNil(o.DnsName) {
		return nil, false
	}
	return o.DnsName, true
}

// HasDnsName returns a boolean if a field has been set.
func (o *OriginPoolOriginServerPublicName) HasDnsName() bool {
	if o != nil && !IsNil(o.DnsName) {
		return true
	}

	return false
}

// SetDnsName gets a reference to the given string and assigns it to the DnsName field.
func (o *OriginPoolOriginServerPublicName) SetDnsName(v string) {
	o.DnsName = &v
}

// GetRefreshInterval returns the RefreshInterval field value if set, zero value otherwise.
func (o *OriginPoolOriginServerPublicName) GetRefreshInterval() int64 {
	if o == nil || IsNil(o.RefreshInterval) {
		var ret int64
		return ret
	}
	return *o.RefreshInterval
}

// GetRefreshIntervalOk returns a tuple with the RefreshInterval field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OriginPoolOriginServerPublicName) GetRefreshIntervalOk() (*int64, bool) {
	if o == nil || IsNil(o.RefreshInterval) {
		return nil, false
	}
	return o.RefreshInterval, true
}

// HasRefreshInterval returns a boolean if a field has been set.
func (o *OriginPoolOriginServerPublicName) HasRefreshInterval() bool {
	if o != nil && !IsNil(o.RefreshInterval) {
		return true
	}

	return false
}

// SetRefreshInterval gets a reference to the given int64 and assigns it to the RefreshInterval field.
func (o *OriginPoolOriginServerPublicName) SetRefreshInterval(v int64) {
	o.RefreshInterval = &v
}

func (o OriginPoolOriginServerPublicName) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OriginPoolOriginServerPublicName) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DnsName) {
		toSerialize["dns_name"] = o.DnsName
	}
	if !IsNil(o.RefreshInterval) {
		toSerialize["refresh_interval"] = o.RefreshInterval
	}
	return toSerialize, nil
}

type NullableOriginPoolOriginServerPublicName struct {
	value *OriginPoolOriginServerPublicName
	isSet bool
}

func (v NullableOriginPoolOriginServerPublicName) Get() *OriginPoolOriginServerPublicName {
	return v.value
}

func (v *NullableOriginPoolOriginServerPublicName) Set(val *OriginPoolOriginServerPublicName) {
	v.value = val
	v.isSet = true
}

func (v NullableOriginPoolOriginServerPublicName) IsSet() bool {
	return v.isSet
}

func (v *NullableOriginPoolOriginServerPublicName) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOriginPoolOriginServerPublicName(val *OriginPoolOriginServerPublicName) *NullableOriginPoolOriginServerPublicName {
	return &NullableOriginPoolOriginServerPublicName{value: val, isSet: true}
}

func (v NullableOriginPoolOriginServerPublicName) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOriginPoolOriginServerPublicName) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


