/*
F5 Distributed Cloud Services API for ves.io.schema.views.origin_pool

Origin pool is a view to create cluster and endpoints that can be used in HTTP loadbalancer or TCP loadbalancer  It will create following child objects  * cluster * endpoints * healthcheck

API version: 
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the OriginPoolReplaceRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OriginPoolReplaceRequest{}

// OriginPoolReplaceRequest This is the input message of the 'Replace' RPC
type OriginPoolReplaceRequest struct {
	Metadata *SchemaObjectReplaceMetaType `json:"metadata,omitempty"`
	Spec *ViewsoriginPoolReplaceSpecType `json:"spec,omitempty"`
}

// NewOriginPoolReplaceRequest instantiates a new OriginPoolReplaceRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOriginPoolReplaceRequest() *OriginPoolReplaceRequest {
	this := OriginPoolReplaceRequest{}
	return &this
}

// NewOriginPoolReplaceRequestWithDefaults instantiates a new OriginPoolReplaceRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOriginPoolReplaceRequestWithDefaults() *OriginPoolReplaceRequest {
	this := OriginPoolReplaceRequest{}
	return &this
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *OriginPoolReplaceRequest) GetMetadata() SchemaObjectReplaceMetaType {
	if o == nil || IsNil(o.Metadata) {
		var ret SchemaObjectReplaceMetaType
		return ret
	}
	return *o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OriginPoolReplaceRequest) GetMetadataOk() (*SchemaObjectReplaceMetaType, bool) {
	if o == nil || IsNil(o.Metadata) {
		return nil, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *OriginPoolReplaceRequest) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given SchemaObjectReplaceMetaType and assigns it to the Metadata field.
func (o *OriginPoolReplaceRequest) SetMetadata(v SchemaObjectReplaceMetaType) {
	o.Metadata = &v
}

// GetSpec returns the Spec field value if set, zero value otherwise.
func (o *OriginPoolReplaceRequest) GetSpec() ViewsoriginPoolReplaceSpecType {
	if o == nil || IsNil(o.Spec) {
		var ret ViewsoriginPoolReplaceSpecType
		return ret
	}
	return *o.Spec
}

// GetSpecOk returns a tuple with the Spec field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OriginPoolReplaceRequest) GetSpecOk() (*ViewsoriginPoolReplaceSpecType, bool) {
	if o == nil || IsNil(o.Spec) {
		return nil, false
	}
	return o.Spec, true
}

// HasSpec returns a boolean if a field has been set.
func (o *OriginPoolReplaceRequest) HasSpec() bool {
	if o != nil && !IsNil(o.Spec) {
		return true
	}

	return false
}

// SetSpec gets a reference to the given ViewsoriginPoolReplaceSpecType and assigns it to the Spec field.
func (o *OriginPoolReplaceRequest) SetSpec(v ViewsoriginPoolReplaceSpecType) {
	o.Spec = &v
}

func (o OriginPoolReplaceRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OriginPoolReplaceRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}
	if !IsNil(o.Spec) {
		toSerialize["spec"] = o.Spec
	}
	return toSerialize, nil
}

type NullableOriginPoolReplaceRequest struct {
	value *OriginPoolReplaceRequest
	isSet bool
}

func (v NullableOriginPoolReplaceRequest) Get() *OriginPoolReplaceRequest {
	return v.value
}

func (v *NullableOriginPoolReplaceRequest) Set(val *OriginPoolReplaceRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableOriginPoolReplaceRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableOriginPoolReplaceRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOriginPoolReplaceRequest(val *OriginPoolReplaceRequest) *NullableOriginPoolReplaceRequest {
	return &NullableOriginPoolReplaceRequest{value: val, isSet: true}
}

func (v NullableOriginPoolReplaceRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOriginPoolReplaceRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


