/*
F5 Distributed Cloud Services API for ves.io.schema.views.origin_pool

Origin pool is a view to create cluster and endpoints that can be used in HTTP loadbalancer or TCP loadbalancer  It will create following child objects  * cluster * endpoints * healthcheck

API version: 
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the OriginPoolOriginServerPublicIP type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OriginPoolOriginServerPublicIP{}

// OriginPoolOriginServerPublicIP Specify origin server with public IP address
type OriginPoolOriginServerPublicIP struct {
	// Exclusive with []  Public IPV4 address  Example: ` \"8.8.8.8\"`  Validation Rules:   ves.io.schema.rules.string.ipv4: true 
	Ip *string `json:"ip,omitempty"`
}

// NewOriginPoolOriginServerPublicIP instantiates a new OriginPoolOriginServerPublicIP object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOriginPoolOriginServerPublicIP() *OriginPoolOriginServerPublicIP {
	this := OriginPoolOriginServerPublicIP{}
	return &this
}

// NewOriginPoolOriginServerPublicIPWithDefaults instantiates a new OriginPoolOriginServerPublicIP object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOriginPoolOriginServerPublicIPWithDefaults() *OriginPoolOriginServerPublicIP {
	this := OriginPoolOriginServerPublicIP{}
	return &this
}

// GetIp returns the Ip field value if set, zero value otherwise.
func (o *OriginPoolOriginServerPublicIP) GetIp() string {
	if o == nil || IsNil(o.Ip) {
		var ret string
		return ret
	}
	return *o.Ip
}

// GetIpOk returns a tuple with the Ip field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OriginPoolOriginServerPublicIP) GetIpOk() (*string, bool) {
	if o == nil || IsNil(o.Ip) {
		return nil, false
	}
	return o.Ip, true
}

// HasIp returns a boolean if a field has been set.
func (o *OriginPoolOriginServerPublicIP) HasIp() bool {
	if o != nil && !IsNil(o.Ip) {
		return true
	}

	return false
}

// SetIp gets a reference to the given string and assigns it to the Ip field.
func (o *OriginPoolOriginServerPublicIP) SetIp(v string) {
	o.Ip = &v
}

func (o OriginPoolOriginServerPublicIP) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OriginPoolOriginServerPublicIP) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Ip) {
		toSerialize["ip"] = o.Ip
	}
	return toSerialize, nil
}

type NullableOriginPoolOriginServerPublicIP struct {
	value *OriginPoolOriginServerPublicIP
	isSet bool
}

func (v NullableOriginPoolOriginServerPublicIP) Get() *OriginPoolOriginServerPublicIP {
	return v.value
}

func (v *NullableOriginPoolOriginServerPublicIP) Set(val *OriginPoolOriginServerPublicIP) {
	v.value = val
	v.isSet = true
}

func (v NullableOriginPoolOriginServerPublicIP) IsSet() bool {
	return v.isSet
}

func (v *NullableOriginPoolOriginServerPublicIP) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOriginPoolOriginServerPublicIP(val *OriginPoolOriginServerPublicIP) *NullableOriginPoolOriginServerPublicIP {
	return &NullableOriginPoolOriginServerPublicIP{value: val, isSet: true}
}

func (v NullableOriginPoolOriginServerPublicIP) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOriginPoolOriginServerPublicIP) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


